version: '3.8'
services:
  rasa:
    image: rasa_custom:latest
    ports:
      - "5005:5005"
    environment:
      DB_DATABASE: "rasa"
    depends_on:
      - db
    volumes:
      - ./app:/app

  action_server:
    image: rasa_action:latest
    ports:
      - "5055:5055"
    volumes:
      - ./app/actions:/app/actions

  db:
    restart: always
    image: "bitnami/postgresql:11.7.0"
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: "admin"
      POSTGRESQL_PASSWORD: "admin"
      POSTGRESQL_DATABASE: "rasa"
    volumes:
      - ./db:/bitnami/postgresql
